# Hapus baris 'version' karena sudah tidak direkomendasikan
services:
  # Layanan Aplikasi Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_net
    # 'depends_on' dihapus dari sini

  # Layanan Web Server Nginx
  webserver:
    image: nginx:stable-alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_net
    depends_on: # <-- Pindahkan ke sini
      - app      # <-- Webserver menunggu app siap

networks:
  laravel_net:
    driver: bridge
